version: '3.9'

services:
  app:
    image: 'flight-search:latest'
    build:
      context: .
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - "9595-9597:8080"
    networks:
      - open-weather-network

networks:
  open-weather-network: